spring:
  application:
    name: ${SPRING_APPLICATION_NAME:accounts}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:neko}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761}

info:
  app:
    name: "accounts"
    description: "Syncrosa Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      syncrosa:
        usersservice: DEBUG