version: "3.3"
services:
#  accounts-db:
#    container_name: accounts-db
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: account_service
#    volumes:
#      - ../../users-service/database.sql:/docker-entrypoint-initdb.d/init.sql
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  loans-db:
#    container_name: loans-db
#    image: postgres:latest
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    ports:
#      - 5434:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: secret
#      POSTGRES_INITDB_ARGS: "--data-checksums"
#      POSTGRES_DB: loan_service
#    volumes:
#      - ../../loans-service/database.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - meow-networks
##    extends:
##      file: common-config.yml
##      service: microservice-db-config
#
#  cards-db:
#    container_name: cards-db
#    image: postgres:latest
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    ports:
#      - 5436:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: secret
#      POSTGRES_INITDB_ARGS: "--data-checksums"
#      POSTGRES_DB: card-service
#    volumes:
#      - ../../cards-service/database.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - meow-networks
##    extends:
##      file: common-config.yml
##      service: microservice-db-config

  configserver:
    image: "hikaruyuzu/config-server:s9"
    container_name: configserver
    ports:
      - 8888:8888
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_APPLICATION_NAME: "configserver"

  eurekaserver:
    image: "hikaruyuzu/eureka-server:s9"
    container_name: eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "eurekaserver"

  gatewayserver:
    image: "hikaruyuzu/gateway-server:s9"
    container_name: gatewayserver
    ports:
      - 8072:8072
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: "gatewayserver"
    #    depends_on:
    #      accounts-db:
    #        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  accounts:
    image: "hikaruyuzu/users-service:s9"
    container_name: accounts-service
    ports:
      - 8080:8080
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: "accounts"
#    depends_on:
#      accounts-db:
#        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  loans:
    image: "hikaruyuzu/loans-service:s9"
    container_name: loans-service
    ports:
      - 8090:8090
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "hikaruyuzu/cards-service:s9"
    container_name: cards-service
    ports:
      - 9000:9000
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  meow-networks:
    name: meow-networks
    driver: bridge